_BASE_: [
  '../datasets/ad_bubbles.yml',
  '../runtime.yml',
  './_base_/ppyolo_r50vd_dcn.yml',
  './_base_/optimizer_1x.yml',
  './_base_/ad_ppyolo_reader.yml',
]

snapshot_epoch: 16
weights: output/ppyolo_r50vd_dcn_1x_coco/model_final
